### ISSUE TITLE
Nikon Z focus point examples

### ISSUE THREAD

**Issue by bwanaaa** [ropma/Focus-Points#1]
Thank you for your input on muzzelwhite's plugin. As you requested some sample images but that issue was closed on muzzelwhite, I am providing to you here a dropbox link with the requested data. The location of the focus point in each image is included in the name of the image. So for example an image labeled 'Siemensz14-30 topright' is a photo of the the Siemens star using the Z 14-30 zoom lens where the focus point was placed in the top right of the image.

https://www.dropbox.com/sh/odiz25wsu2q61l0/AAAZQjfejc2X7sJIvw_oDEoBa?dl=0

**Comment by ropma** [comment]
Thanks for the sample images. Currently I'm busy, but maybe I find next month some time to have a look.

**Comment by ropma** [comment]
Solved with https://github.com/musselwhizzle/Focus-Points/issues/152
